const fs = require("fs");
const { promisify } = require("util");
const path = require("path");
const marked = require("marked");
const fm = require("front-matter");
const Handlebars = require("handlebars");
const HTMLMinifier = require("html-minifier");
const emoji = require('node-emoji');
const { assureDir, fromPairs } = require("./util");

const readdir = promisify(fs.readdir);
const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);

const HTML_MINIFIER_OPTIONS = {
  caseSensitive: true,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: false,
  customAttrAssign: [],
  customAttrSurround: [],
  customEventAttributes: [ /^on[a-z]{3,}$/ ],
  decodeEntities:	true,
  html5: true,
  ignoreCustomComments:	[],
  ignoreCustomFragments: [],
  includeAutoGeneratedTags:	true,
  keepClosingSlash: false,
  maxLineLength: false,
  minifyJS: false,
  minifyURLs: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: true,
  processConditionalComments: false,
  processScripts: [],
  quoteCharacter:	'"',
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: false,
  useShortDoctype: true,
};

/**
 * @todo
 * Support nested pages
 * Resolve referred resources (images, fonts...): custom statement or ./
 * Support .handlebars and .html
 */
module.exports = async function build(directory) {
  const pagesDir = path.join(directory, "pages");
  const layoutsDir = path.join(directory, "layouts");
  const partialsDir = path.join(directory, "partials");
  const buildDir = path.join(directory, "build");
  const dataDir = path.join(directory, "data");
  const pages = await readdir(pagesDir);
  const partials = await readdir(partialsDir);
  const dataFiles = await readdir(dataDir);
  const layouts = {};
  const data = fromPairs(
    await Promise.all(
      dataFiles.map(async dataFile => [
        path.parse(dataFile).name,
        JSON.parse(
          await readFile(path.join(dataDir, dataFile), { encoding: "utf-8" })
        )
      ])
    )
  );

  await Promise.all(
    partials.map(async partial => {
      const { name } = path.parse(partial);
      Handlebars.registerPartial(
        name,
        await readFile(path.join(partialsDir, partial), { encoding: "utf-8" })
      );
    })
  );

  assureDir(buildDir);

  await Promise.all(
    // assume pages
    pages.map(async page => {
      const pageName = path.parse(page).name;
      const pagePath = path.join(pagesDir, page);
      const pageRawContent = await readFile(pagePath, { encoding: "utf-8" });
      const { body, attributes } = fm(pageRawContent);
      const content = emoji.emojify(marked.parse(body, { gfm: true }));
      // assume layout
      const layout =
        layouts[attributes.layout] ||
        Handlebars.compile(
          await readFile(path.join(layoutsDir, attributes.layout + ".hbs"), {
            encoding: "utf-8"
          })
        );
      const builtPageFileName = pageName + ".html";
      const builtPage = layout({
        page: {
          attributes,
          content
        },
        ...data
      });
      await writeFile(
        path.join(buildDir, builtPageFileName),
        HTMLMinifier.minify(builtPage, HTML_MINIFIER_OPTIONS)
      );
      console.info("Built", builtPageFileName);
    })
  ).catch(console.error);
};
