const HTMLMinifier = require("html-minifier");

const OPTIONS = {
  caseSensitive: true,
  collapseBooleanAttributes: false,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  conservativeCollapse: false,
  customAttrAssign: [],
  customAttrSurround: [],
  customEventAttributes: [/^on[a-z]{3,}$/],
  decodeEntities: true,
  html5: true,
  ignoreCustomComments: [],
  ignoreCustomFragments: [],
  includeAutoGeneratedTags: true,
  keepClosingSlash: false,
  maxLineLength: false,
  minifyJS: false,
  minifyURLs: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: true,
  processConditionalComments: false,
  processScripts: [],
  quoteCharacter: '"',
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,
  removeTagWhitespace: false,
  sortAttributes: false,
  sortClassName: false,
  trimCustomFragments: false,
  useShortDoctype: true
};

module.exports = function minify(html) {
  return HTMLMinifier.minify(html, OPTIONS);
};
